version: "3.8"

services:
  app:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
    environment:
      - DATABASE_URL=postgres:///task.db
    depends_on:
      - db
  db: 
    image: postgres:13
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=task.db
    volumes:
      - ./data:/var/lib/postgresql/data

volumes:
  postgres_data: